import json
import os
import sqlite3
from contextlib import asynccontextmanager, contextmanager
from datetime import datetime, timezone
from pathlib import Path
from time import perf_counter
from typing import Annotated
from uuid import uuid4

from fastapi import FastAPI, HTTPException, Path as ApiPath, Request, Response
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from monitor import MonitorConfig, install_logging, monitor

from .demo_faults import (
    DemoFaultConflictError,
    DemoFaultUnavailableError,
    demo_fault_manager,
)
from .logging_config import configure_logging, logger, shutdown_logging

MAX_PRICE = 1_000_000_000
MAX_PRODUCT_ID = 2**63 - 1
MAX_QUANTITY = 99
DEFAULT_DB_PATH = "/data/shop.db"
PRODUCT_FIELDS = ("name", "category", "price", "icon", "color", "description")
PRODUCT_SELECT = ", ".join(("id", *PRODUCT_FIELDS))
PRODUCT_TEXT_FIELDS = ("name", "category", "icon", "color", "description")
HEX_COLOR = r"^#[0-9a-fA-F]{6}$"

# These rows are inserted by migration 1 only. Product ids are deliberately
# generated by SQLite so later CRUD operations keep AUTOINCREMENT semantics.
SEED_PRODUCTS = (
    dict(name="晨光陶瓷杯", category="居家生活", price=480, icon="☕", color="#e8d9c5", description="溫潤霧面釉色，盛裝每個美好的早晨。"),
    dict(name="日常帆布托特包", category="隨身好物", price=690, icon="👜", color="#dbe3d4", description="厚磅純棉、大容量，帶著喜歡的生活出門。"),
    dict(name="木質香氛蠟燭", category="居家生活", price=880, icon="🕯️", color="#ead9d3", description="雪松與佛手柑，為夜晚留一點安靜。"),
    dict(name="靈感方格筆記本", category="文具選物", price=320, icon="📓", color="#d5dedf", description="平攤裝訂與細緻紙張，收集生活的小靈感。"),
    dict(name="輕旅保溫水瓶", category="隨身好物", price=780, icon="🥤", color="#e5dfcd", description="輕巧不鏽鋼瓶身，剛剛好的隨行陪伴。"),
    dict(name="桌上綠意盆栽", category="居家生活", price=560, icon="🪴", color="#d9e3d7", description="一抹自然綠意，讓工作桌也能深呼吸。"),
)

CREATE_MIGRATIONS_TABLE = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY
)
"""
CREATE_ORDERS_TABLE = """
CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    payload TEXT NOT NULL
)
"""
CREATE_PRODUCTS_TABLE = """
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price INTEGER NOT NULL,
    icon TEXT NOT NULL,
    color TEXT NOT NULL,
    description TEXT NOT NULL
)
"""
CREATE_CARTS_TABLE = """
CREATE TABLE IF NOT EXISTS carts (
    id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL
)
"""
CREATE_CART_ITEMS_TABLE = """
CREATE TABLE IF NOT EXISTS cart_items (
    cart_id TEXT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    PRIMARY KEY (cart_id, product_id)
)
"""


def database_path() -> Path:
    """Return the configured SQLite path and fail clearly for bad configuration."""
    configured = os.getenv("DB_PATH", DEFAULT_DB_PATH).strip()
    if not configured:
        raise RuntimeError("DB_PATH must point to a SQLite database file")
    return Path(configured)


@contextmanager
def connect():
    path = database_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    db = sqlite3.connect(path, timeout=10)
    try:
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA foreign_keys = ON")
        # sqlite3.Connection commits or rolls back on exit, but does not close
        # itself. Keep both responsibilities explicit at every call site.
        with db:
            yield db
    finally:
        db.close()


def init_db() -> None:
    """Run the one-time schema migration in one SQLite transaction."""
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        db.execute(CREATE_MIGRATIONS_TABLE)
        # CREATE IF NOT EXISTS leaves an existing orders table and its payloads
        # untouched while upgrading databases created by the first API version.
        db.execute(CREATE_ORDERS_TABLE)
        db.execute(CREATE_PRODUCTS_TABLE)
        db.execute(CREATE_CARTS_TABLE)
        db.execute(CREATE_CART_ITEMS_TABLE)

        migrated = db.execute(
            "SELECT 1 FROM schema_migrations WHERE version = 1"
        ).fetchone()
        if migrated is None:
            for product in SEED_PRODUCTS:
                db.execute(
                    """
                    INSERT INTO products
                        (name, category, price, icon, color, description)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """,
                    tuple(product[field] for field in PRODUCT_FIELDS),
                )
            db.execute("INSERT INTO schema_migrations (version) VALUES (1)")


class DemoFaultActivation(BaseModel):
    model_config = ConfigDict(extra="forbid")

    fault_id: str = Field(min_length=1, max_length=64)

    @field_validator("fault_id", mode="before")
    @classmethod
    def strip_fault_id(cls, value):
        return value.strip() if isinstance(value, str) else value


class DemoFaultCard(BaseModel):
    model_config = ConfigDict(extra="forbid")

    fault_id: str
    title: str
    description: str


class DemoFaultActive(BaseModel):
    model_config = ConfigDict(extra="forbid")

    fault_id: str
    started_at: str
    expires_at: str | None = None
    remaining_seconds: float
    status: str


class DemoFaultsResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cards: list[DemoFaultCard]
    active: DemoFaultActive | None = None
    lease_seconds: int
    delay_seconds: int


@asynccontextmanager
async def lifespan(_app: FastAPI):
    configure_logging()
    install_logging(logger)
    try:
        logger.info("application startup")
        logger.info("database migration started")
        init_db()
        await demo_fault_manager.start()
        logger.info("database migration completed")
        yield
    finally:
        logger.info("application shutdown")
        try:
            await demo_fault_manager.shutdown()
        finally:
            shutdown_logging()


app = FastAPI(title="日日選物 API", lifespan=lifespan)


def _is_checkout_request(method: str, path: str) -> bool:
    return method == "POST" and (
        path == "/api/orders"
        or (path.startswith("/api/carts/") and path.endswith("/checkout"))
    )


@app.middleware("http")
async def request_logging_middleware(request: Request, call_next):
    started_at = perf_counter()
    path = request.url.path.replace("\r", r"\r").replace("\n", r"\n")
    status_code = 500
    affected_fault_id = None
    try:
        if _is_checkout_request(request.method, path):
            affected_fault_id = demo_fault_manager.checkout_fault_id()
            if affected_fault_id == "checkout_delay":
                await demo_fault_manager.wait_for_checkout_delay()
        response = await call_next(request)
        status_code = response.status_code
        return response
    except Exception:
        logger.exception(
            "unexpected request error method=%s path=%s fault_id=%s",
            request.method,
            path,
            affected_fault_id,
        )
        raise
    finally:
        duration_ms = (perf_counter() - started_at) * 1000
        if affected_fault_id is not None:
            logger.info(
                "demo fault affected request fault_id=%s method=%s path=%s status=%s duration_ms=%.2f",
                affected_fault_id,
                request.method,
                path,
                status_code,
                duration_ms,
            )
        logger.info(
            "request method=%s path=%s status=%s duration_ms=%.2f",
            request.method,
            path,
            status_code,
            duration_ms,
        )


@app.get("/api/demo-faults", response_model=DemoFaultsResponse)
async def get_demo_faults():
    return await demo_fault_manager.get_state()


@app.post("/api/demo-faults", response_model=DemoFaultsResponse)
async def activate_demo_fault(fault: DemoFaultActivation):
    try:
        return await demo_fault_manager.activate(fault.fault_id)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    except DemoFaultConflictError as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc
    except DemoFaultUnavailableError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@app.delete("/api/demo-faults", response_model=DemoFaultsResponse)
async def deactivate_demo_fault():
    return await demo_fault_manager.deactivate()


StrictProductId = Annotated[int, Field(strict=True, gt=0, le=MAX_PRODUCT_ID)]
StrictQuantity = Annotated[int, Field(strict=True, ge=1, le=MAX_QUANTITY)]
StrictPrice = Annotated[int, Field(strict=True, gt=0, le=MAX_PRICE)]


class ProductFields(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=80)
    category: str = Field(min_length=1, max_length=40)
    price: StrictPrice
    icon: str = Field(min_length=1, max_length=32)
    color: str = Field(pattern=HEX_COLOR)
    description: str = Field(max_length=2000)

    @field_validator(*PRODUCT_TEXT_FIELDS, mode="before")
    @classmethod
    def strip_text(cls, value):
        return value.strip() if isinstance(value, str) else value


class ProductCreate(ProductFields):
    """The complete six-field payload used by POST and PUT."""


class ProductPatch(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str | None = Field(default=None, min_length=1, max_length=80)
    category: str | None = Field(default=None, min_length=1, max_length=40)
    price: StrictPrice | None = None
    icon: str | None = Field(default=None, min_length=1, max_length=32)
    color: str | None = Field(default=None, pattern=HEX_COLOR)
    description: str | None = Field(default=None, max_length=2000)

    @model_validator(mode="before")
    @classmethod
    def reject_null_and_empty_payload(cls, value):
        if isinstance(value, dict):
            if not value:
                raise ValueError("至少需要一個商品欄位")
            if any(raw_value is None for raw_value in value.values()):
                raise ValueError("商品欄位不可為 null")
        return value

    @field_validator(*PRODUCT_TEXT_FIELDS, mode="before")
    @classmethod
    def strip_text(cls, value):
        return value.strip() if isinstance(value, str) else value

    @model_validator(mode="after")
    def require_field(self):
        if not self.model_fields_set:
            raise ValueError("至少需要一個商品欄位")
        return self


class ProductResponse(ProductFields):
    id: StrictProductId


class Item(BaseModel):
    model_config = ConfigDict(extra="forbid")

    product_id: StrictProductId
    quantity: StrictQuantity


class Checkout(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=80)
    address: str = Field(min_length=5, max_length=300)
    items: list[Item] = Field(min_length=1, max_length=50)

    @field_validator("name", "address", mode="before")
    @classmethod
    def strip_text(cls, value):
        return value.strip() if isinstance(value, str) else value


class ShippingDetails(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1, max_length=80)
    address: str = Field(min_length=5, max_length=300)

    @field_validator("name", "address", mode="before")
    @classmethod
    def strip_text(cls, value):
        return value.strip() if isinstance(value, str) else value


class CartItemInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    product_id: StrictProductId
    quantity: StrictQuantity


class CartQuantityInput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    quantity: StrictQuantity


class CartItemResponse(ProductResponse):
    product_id: StrictProductId
    quantity: StrictQuantity
    line_total: int = Field(ge=0)


class CartResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    items: list[CartItemResponse]
    total: int = Field(ge=0)


class OrderLineResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    product_id: StrictProductId
    name: str
    price: StrictPrice
    quantity: StrictQuantity


class OrderResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    created_at: str
    total: int = Field(ge=0)
    items: list[OrderLineResponse]


def _product_payload(row: sqlite3.Row) -> dict:
    return {field: row[field] for field in ("id", *PRODUCT_FIELDS)}


def _find_product(db: sqlite3.Connection, product_id: int) -> sqlite3.Row | None:
    return db.execute(
        f"SELECT {PRODUCT_SELECT} FROM products WHERE id = ?",
        (product_id,),
    ).fetchone()


def _require_cart(db: sqlite3.Connection, cart_id: str) -> None:
    if db.execute("SELECT 1 FROM carts WHERE id = ?", (cart_id,)).fetchone() is None:
        raise HTTPException(status_code=404, detail="購物車不存在。")


def _cart_items(db: sqlite3.Connection, cart_id: str) -> list[dict]:
    rows = db.execute(
        """
        SELECT p.id, p.name, p.category, p.price, p.icon, p.color,
               p.description, ci.product_id, ci.quantity,
               p.price * ci.quantity AS line_total
          FROM cart_items AS ci
          JOIN products AS p ON p.id = ci.product_id
         WHERE ci.cart_id = ?
         ORDER BY ci.product_id
        """,
        (cart_id,),
    ).fetchall()
    items = []
    for row in rows:
        item = _product_payload(row)
        item.update(
            product_id=row["product_id"],
            quantity=row["quantity"],
            line_total=row["line_total"],
        )
        items.append(item)
    return items


def _cart_payload(db: sqlite3.Connection, cart_id: str) -> dict:
    _require_cart(db, cart_id)
    items = _cart_items(db, cart_id)
    return {
        "id": cart_id,
        "items": items,
        "total": sum(item["line_total"] for item in items),
    }


def _new_order(lines: list[dict]) -> dict:
    return {
        "id": uuid4().hex,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "total": sum(line["price"] * line["quantity"] for line in lines),
        "items": lines,
    }


def _insert_order(
    db: sqlite3.Connection,
    order: dict,
    name: str,
    address: str,
) -> None:
    payload = {**order, "name": name, "address": address}
    db.execute(
        "INSERT INTO orders (id, created_at, payload) VALUES (?, ?, ?)",
        (
            order["id"],
            order["created_at"],
            json.dumps(payload, ensure_ascii=False),
        ),
    )


def _order_lines_from_items(
    db: sqlite3.Connection,
    items: list[Item],
) -> list[dict]:
    quantities: dict[int, int] = {}
    product_rows: dict[int, sqlite3.Row] = {}
    for item in items:
        row = product_rows.get(item.product_id)
        if row is None:
            row = _find_product(db, item.product_id)
            if row is None:
                # Keep the original orders endpoint's 400 behavior.
                raise HTTPException(status_code=400, detail="商品不存在，請重新整理商品列表。")
            product_rows[item.product_id] = row
        quantity = quantities.get(item.product_id, 0) + item.quantity
        if quantity > MAX_QUANTITY:
            raise HTTPException(status_code=400, detail="每件商品最多可購買 99 件。")
        quantities[item.product_id] = quantity

    return [
        {
            "product_id": product_id,
            "name": product_rows[product_id]["name"],
            "price": product_rows[product_id]["price"],
            "quantity": quantity,
        }
        for product_id, quantity in quantities.items()
    ]


@app.get("/api/health")
@monitor(MonitorConfig(name="GET /api/health", monitor_id="shop.health", level="WARNING"))
def health():
    with connect() as db:
        _query(db, "SELECT 1 FROM orders LIMIT 1")
    return {"status": "ok"}


@app.get("/api/products", response_model=list[ProductResponse])
@monitor(MonitorConfig(name="GET /api/products", monitor_id="shop.products", level="WARNING"))
def products():
    with connect() as db:
        rows = _query(db,
            f"SELECT {PRODUCT_SELECT} FROM products ORDER BY id"
        )
    return [_product_payload(row) for row in rows]


@monitor(MonitorConfig(name="shop database query", monitor_id="shop.db.query", level="WARNING"))
def _query(db: sqlite3.Connection, sql: str):
    return db.execute(sql).fetchall()


@app.get("/api/products/{product_id}", response_model=ProductResponse)
def get_product(product_id: int = ApiPath(..., gt=0, le=MAX_PRODUCT_ID)):
    with connect() as db:
        row = _find_product(db, product_id)
    if row is None:
        raise HTTPException(status_code=404, detail="商品不存在。")
    return _product_payload(row)


@app.post("/api/products", response_model=ProductResponse, status_code=201)
def create_product(product: ProductCreate):
    values = product.model_dump()
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        cursor = db.execute(
            """
            INSERT INTO products
                (name, category, price, icon, color, description)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            tuple(values[field] for field in PRODUCT_FIELDS),
        )
        row = _find_product(db, cursor.lastrowid)
    return _product_payload(row)


@app.put("/api/products/{product_id}", response_model=ProductResponse)
def replace_product(
    product: ProductCreate,
    product_id: int = ApiPath(..., gt=0, le=MAX_PRODUCT_ID),
):
    values = product.model_dump()
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        if _find_product(db, product_id) is None:
            raise HTTPException(status_code=404, detail="商品不存在。")
        db.execute(
            """
            UPDATE products
               SET name = ?, category = ?, price = ?, icon = ?, color = ?, description = ?
             WHERE id = ?
            """,
            tuple(values[field] for field in PRODUCT_FIELDS) + (product_id,),
        )
        row = _find_product(db, product_id)
    return _product_payload(row)


@app.patch("/api/products/{product_id}", response_model=ProductResponse)
def patch_product(
    product: ProductPatch,
    product_id: int = ApiPath(..., gt=0, le=MAX_PRODUCT_ID),
):
    values = product.model_dump(exclude_unset=True)
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        if _find_product(db, product_id) is None:
            raise HTTPException(status_code=404, detail="商品不存在。")
        assignments = ", ".join(f"{field} = ?" for field in values)
        db.execute(
            f"UPDATE products SET {assignments} WHERE id = ?",
            tuple(values.values()) + (product_id,),
        )
        row = _find_product(db, product_id)
    return _product_payload(row)


@app.delete("/api/products/{product_id}", status_code=204)
def delete_product(product_id: int = ApiPath(..., gt=0, le=MAX_PRODUCT_ID)):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        deleted = db.execute(
            "DELETE FROM products WHERE id = ?", (product_id,)
        ).rowcount
        if deleted == 0:
            raise HTTPException(status_code=404, detail="商品不存在。")
    return Response(status_code=204)


@app.post("/api/carts", response_model=CartResponse, status_code=201)
def create_cart():
    cart_id = uuid4().hex
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        db.execute(
            "INSERT INTO carts (id, created_at) VALUES (?, ?)",
            (cart_id, datetime.now(timezone.utc).isoformat()),
        )
        return _cart_payload(db, cart_id)


@app.get("/api/carts/{cart_id}", response_model=CartResponse)
def get_cart(cart_id: str = ApiPath(..., min_length=1)):
    with connect() as db:
        db.execute("BEGIN")
        return _cart_payload(db, cart_id)


@app.delete("/api/carts/{cart_id}", status_code=204)
def delete_cart(cart_id: str = ApiPath(..., min_length=1)):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        deleted = db.execute("DELETE FROM carts WHERE id = ?", (cart_id,)).rowcount
        if deleted == 0:
            raise HTTPException(status_code=404, detail="購物車不存在。")
    return Response(status_code=204)


@app.post("/api/carts/{cart_id}/items", response_model=CartResponse)
def add_cart_item(
    item: CartItemInput,
    cart_id: str = ApiPath(..., min_length=1),
):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        _require_cart(db, cart_id)
        if _find_product(db, item.product_id) is None:
            raise HTTPException(status_code=404, detail="商品不存在。")
        current = db.execute(
            "SELECT quantity FROM cart_items WHERE cart_id = ? AND product_id = ?",
            (cart_id, item.product_id),
        ).fetchone()
        if current is None:
            db.execute(
                "INSERT INTO cart_items (cart_id, product_id, quantity) VALUES (?, ?, ?)",
                (cart_id, item.product_id, item.quantity),
            )
        else:
            quantity = current["quantity"] + item.quantity
            if quantity > MAX_QUANTITY:
                raise HTTPException(status_code=400, detail="每件商品最多可購買 99 件。")
            db.execute(
                "UPDATE cart_items SET quantity = ? WHERE cart_id = ? AND product_id = ?",
                (quantity, cart_id, item.product_id),
            )
        return _cart_payload(db, cart_id)


@app.get("/api/carts/{cart_id}/items", response_model=list[CartItemResponse])
def get_cart_items(cart_id: str = ApiPath(..., min_length=1)):
    with connect() as db:
        db.execute("BEGIN")
        _require_cart(db, cart_id)
        return _cart_items(db, cart_id)


@app.patch(
    "/api/carts/{cart_id}/items/{product_id}",
    response_model=CartResponse,
)
def set_cart_item_quantity(
    quantity: CartQuantityInput,
    cart_id: str = ApiPath(..., min_length=1),
    product_id: int = ApiPath(..., gt=0, le=MAX_PRODUCT_ID),
):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        _require_cart(db, cart_id)
        updated = db.execute(
            """
            UPDATE cart_items
               SET quantity = ?
             WHERE cart_id = ? AND product_id = ?
            """,
            (quantity.quantity, cart_id, product_id),
        ).rowcount
        if updated == 0:
            raise HTTPException(status_code=404, detail="購物車商品不存在。")
        return _cart_payload(db, cart_id)


@app.delete(
    "/api/carts/{cart_id}/items/{product_id}",
    response_model=CartResponse,
)
def delete_cart_item(
    cart_id: str = ApiPath(..., min_length=1),
    product_id: int = ApiPath(..., gt=0, le=MAX_PRODUCT_ID),
):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        _require_cart(db, cart_id)
        deleted = db.execute(
            "DELETE FROM cart_items WHERE cart_id = ? AND product_id = ?",
            (cart_id, product_id),
        ).rowcount
        if deleted == 0:
            raise HTTPException(status_code=404, detail="購物車商品不存在。")
        return _cart_payload(db, cart_id)


@app.delete("/api/carts/{cart_id}/items", response_model=CartResponse)
def clear_cart(cart_id: str = ApiPath(..., min_length=1)):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        _require_cart(db, cart_id)
        db.execute("DELETE FROM cart_items WHERE cart_id = ?", (cart_id,))
        return _cart_payload(db, cart_id)


@app.post(
    "/api/carts/{cart_id}/checkout",
    response_model=OrderResponse,
    status_code=201,
)
def checkout_cart(
    shipping: ShippingDetails,
    cart_id: str = ApiPath(..., min_length=1),
):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        _require_cart(db, cart_id)
        rows = db.execute(
            """
            SELECT ci.product_id, p.name, p.price, ci.quantity
              FROM cart_items AS ci
              JOIN products AS p ON p.id = ci.product_id
             WHERE ci.cart_id = ?
             ORDER BY ci.product_id
            """,
            (cart_id,),
        ).fetchall()
        if not rows:
            raise HTTPException(status_code=400, detail="購物車是空的。")
        lines = [
            {
                "product_id": row["product_id"],
                "name": row["name"],
                "price": row["price"],
                "quantity": row["quantity"],
            }
            for row in rows
        ]
        order = _new_order(lines)
        _insert_order(db, order, shipping.name, shipping.address)
        db.execute("DELETE FROM cart_items WHERE cart_id = ?", (cart_id,))
        if demo_fault_manager.checkout_fault_id() == "checkout_exception":
            # Keep this failure after both writes so the transaction rolls
            # back the order insert and cart clear together.
            raise RuntimeError("demo fault checkout_exception")
        return order


@app.post("/api/orders", response_model=OrderResponse, status_code=201)
def create_order(checkout: Checkout):
    with connect() as db:
        db.execute("BEGIN IMMEDIATE")
        lines = _order_lines_from_items(db, checkout.items)
        order = _new_order(lines)
        _insert_order(db, order, checkout.name, checkout.address)
        if demo_fault_manager.checkout_fault_id() == "checkout_exception":
            # The exception is intentionally raised before the context
            # manager commits the order transaction.
            raise RuntimeError("demo fault checkout_exception")
        return order
